version: "3.9"

services:
  idp:
    image: idp
    build:
      context: ./idp/
      target: test-idp
    command:
      - start-dev
    networks:
      - net
    ports:
      - "8080:8080"
      - "8443:8443"
    expose:
      - "8080"
      - "8443"

  idp-config:
    image: idp-config
    build:
      context: ./idp-config/
      target: idp-config
    depends_on:
      idp:
        condition: service_healthy
    networks:
      - net

  events-source:
    image: events-source
    build:
      context: ./
      dockerfile: events-source.dockerfile
      target: events-source
    ports:
      - "8081:8081"
    expose:
      - "8081"
    networks:
      - net

networks:
  net:
